apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ankrchain-4
spec:
  selector:
    matchLabels:
      app: ankr-chain
      id: ankrchain-4
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  serviceName: ankrchain-4
  template:
    metadata:
      labels:
        app: ankr-chain
        id: ankrchain-4
    spec:
      imagePullSecrets:
      - name: aws-ecr
      volumes:
      - name: tendermint-pvc-4
        persistentVolumeClaim:
          claimName: tendermint-pvc-4
      containers:
      - name: ankrchain
        image: 815280425737.dkr.ecr.us-west-2.amazonaws.com/ankr-chain:feat
        imagePullPolicy: Always
        ports:
        - name: p2p-4
          containerPort: 26656
        - name: rpc
          containerPort: 26657
        - name: abci
          containerPort: 26658
        volumeMounts:
        - name: tendermint-pvc-4
          mountPath: /ankrchain/data